CREATE TABLE "sybaseadmin"."D_AGE" (
		"AGEID" "SMALL_IDENTIFIER" NOT NULL,
	"AGE" "SMALL_NUMBER" NULL,
	"AGEBAND" "AGE_RANGE" NULL,
	"SiteID" "SURROGATE_KEY" NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	PRIMARY KEY ( "AGEID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_AGE" ADD PRIMARY KEY ( "AGEID" ASC );

ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_AGE_GAM_D_AGE" NOT NULL FOREIGN KEY ( "AGEID" ASC ) REFERENCES "sybaseadmin"."D_AGE" ( "AGEID" );

CREATE HG INDEX "ASIQ_IDX_T206_C1_HG" ON "sybaseadmin"."D_AGE" ("AGEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AGE_HG" ON "sybaseadmin"."D_AGE" ("AGE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE UNIQUE HG INDEX "IDX_Age_HG_UNQ" ON "sybaseadmin"."D_AGE" ("AGE" ASC, "SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AGEBAND_HG" ON "sybaseadmin"."D_AGE" ("AGEBAND" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_AGE" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
