CREATE TABLE "sybaseadmin"."D_CASINOLOCATION" (
		"CASINOLOCID" "IDENTIFIER" NOT NULL,
	"LOCTYPCODE" "TYPE_CODE" NOT NULL,
	"EGM_AREA" "Short_Cde" NULL,
	"GAMINGAREA" "TYPE_CODE" NULL,
	"PITNUM" "LOCATION_SUB_CODE" NULL,
	"SiteID" "SURROGATE_KEY" NOT NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	"ETLJobDtlID" "SURROGATE_KEY" NOT NULL,
	PRIMARY KEY ( "CASINOLOCID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_CASINOLOCATION" ADD PRIMARY KEY ( "CASINOLOCID" ASC );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATION" ADD CONSTRAINT "FK_Casino_Loc_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATION" ADD CONSTRAINT "FK_Casino_Loc_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );

ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Daily" ADD CONSTRAINT "FK_CIM_PROD_DAILY_CASINOLOC" NOT NULL FOREIGN KEY ( "CasinoLocID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATION" ( "CASINOLOCID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_CASINO" NOT NULL FOREIGN KEY ( "CASINOLOCATIONID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATION" ( "CASINOLOCID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONHOURGAMEAREA" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_CASINO" NOT NULL FOREIGN KEY ( "CASINOLOCATIONID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATION" ( "CASINOLOCID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Config_CasinoLoc" NOT NULL FOREIGN KEY ( "CasinoLocID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATION" ( "CASINOLOCID" );

CREATE HG INDEX "ASIQ_IDX_T1190_C6_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T1190_I8_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("CASINOLOCID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T888_C8_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE UNIQUE HG INDEX "IDX_Casino_Loc_HG_UNIQ" ON "sybaseadmin"."D_CASINOLOCATION" ("LOCTYPCODE" ASC, "EGM_AREA" ASC, "PITNUM" ASC, "GAMINGAREA" ASC, "SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_AREA_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("EGM_AREA" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGAREA_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("GAMINGAREA" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LOCTYPCODE_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("LOCTYPCODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PITNUM_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("PITNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_CASINOLOCATION" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
