CREATE TABLE "sybaseadmin"."D_GAMINGMACHINE" (
		"GAMINGMACHINEID" "IDENTIFIER" NOT NULL,
	"MANUFCODE" "MANUFACTURER_CODE" NULL,
	"MANUFNAME" "SHORT_DESCRIPTION" NULL,
	"MACTYP" "MANUFACTURER_CODE" NULL,
	"MACMODELNAME" "SHORT_DESCRIPTION" NULL,
	"DEVICEID" "IDENTIFIER" NOT NULL,
	"SERIALNUM" "SERIAL_NUMBER" NULL,
	"MacModelGrp" "Medium_Catg_Typ_Cde" NULL,
	"MacModelGrpName" "SHORT_NAME" NULL,
	"MaxBillDenomAccepted" "SMALL_NUMBER" NULL,
	"MacTypName" "SHORT_NAME" NULL,
	"SiteID" "SURROGATE_KEY" NOT NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	"TicketInFlg" "TINY_COUNTER" NULL,
	"TicketOutFlg" "TINY_COUNTER" NULL,
	"PAI" "SERIAL_NUMBER" NOT NULL,
	"ETLJobDtlID" "SURROGATE_KEY" NOT NULL,
	PRIMARY KEY ( "GAMINGMACHINEID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_GAMINGMACHINE" ADD PRIMARY KEY ( "GAMINGMACHINEID" ASC );
ALTER TABLE "sybaseadmin"."D_GAMINGMACHINE" ADD CONSTRAINT "FK_Gaming_Mac_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."D_GAMINGMACHINE" ADD CONSTRAINT "FK_Gaming_Mac_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );

ALTER TABLE "sybaseadmin"."F_ATS_Daily_Revenue" ADD CONSTRAINT "FK_ATS_Daily_Rev_GamingMach" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_ATS_Hourly_Poll" ADD CONSTRAINT "FK_ATS_Hourly_Poll_GamingMach" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_ATS_Jackpot_Hit" ADD CONSTRAINT "FK_ATS_Jkp_Hit_GamingMachine" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Bill_Acceptance" ADD CONSTRAINT "FK_Bill_Accept_Mac" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Consolation_Prize_Transactions" ADD CONSTRAINT "FK_Consolation_Prize_GamingMachine" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_DACOM_Bonusing" ADD CONSTRAINT "FK_DACOM_Bonus_Mac" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_FATG_Configuration" ADD CONSTRAINT "FK_F_FATG_Config_GamingMachine" NOT NULL FOREIGN KEY ( "GAMINGMACHINEID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_GAMINGM_D_GAMING" NOT NULL FOREIGN KEY ( "GAMINGMACHINEID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Config" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_License_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Lic_Config_GamingMachine" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Hit" ADD CONSTRAINT "FK_Jkpt_Hit_GamingMachine" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Daily_Balance" ADD CONSTRAINT "FK_JkptDailyBal_GamingMac" NOT NULL FOREIGN KEY ( "GamingMacID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_GamingMachine" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Machine_Daily_Revenue" ADD CONSTRAINT "FK_Mac_Daily_Rev_Mac" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Machine_Hourly_Poll" ADD CONSTRAINT "FK_Mac_Hourly_Poll_Mac" NOT NULL FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_MacDailyGameRev" ADD CONSTRAINT "FK_MacDailyGameRev_GamingMac" NOT NULL FOREIGN KEY ( "GamingMacID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Hits" ADD CONSTRAINT "FK_PromotionHits_GamingMachine" FOREIGN KEY ( "GamingMachineID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );

CREATE HG INDEX "ASIQ_IDX_T1332_C12_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T1332_I17_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("GAMINGMACHINEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T982_C17_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DEVICEID_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("DEVICEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MacModelGrp_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MacModelGrp" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MacModelGrpName_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MacModelGrpName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MACMODELNAME_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MACMODELNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_MACMODELNAME_WD" ON "sybaseadmin"."D_GAMINGMACHINE" ("MACMODELNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MACTYP_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MACTYP" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MacTypName_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MacTypName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MANUFCODE_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MANUFCODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MANUFNAME_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MANUFNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MaxBillDenomAccepted_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("MaxBillDenomAccepted" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PAI_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("PAI" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SERIALNUM_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("SERIALNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TicketInFlg_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("TicketInFlg" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TicketOutFlg_HG" ON "sybaseadmin"."D_GAMINGMACHINE" ("TicketOutFlg" ASC) IN "IQ_ACTIVE_MAIN";
