CREATE TABLE "sybaseadmin"."D_HOUR" (
		"HOURID" "IDENTIFIER" NOT NULL,
	"DAYID" "SMALL_IDENTIFIER" NOT NULL,
	"WEEKID" "SMALL_IDENTIFIER" NOT NULL,
	"MONTHID" "SMALL_IDENTIFIER" NOT NULL,
	"HOURNUMWITHINDAY" "TINY_COUNTER" NULL,
	"GAMINGHOURNUMWITHINDAY" "TINY_COUNTER" NULL,
	"HOURDESC" "BAND_DESCRIPTION" NULL,
	"GAMINGHOURDESC" "BAND_DESCRIPTION" NULL,
	"PEAKHOURIND" "TYPE_CODE" NULL,
	"HOURSSINCE30_06_1994" "COUNTER" NULL,
	"THREEHOURBANDNUM" "TINY_COUNTER" NULL,
	"THREEHOURBANDDESC" "BAND_DESCRIPTION" NULL,
	"FOURHOURBANDNUM" "TINY_COUNTER" NULL,
	"FOURHOURBANDDESC" "BAND_DESCRIPTION" NULL,
	"FULLDT" "FULL_DATE" NULL,
	"DAYNAME" "SHORT_NAME" NULL,
	"DAYSHORTNAME" "ABBREVIATION" NULL,
	"PEAKDAYFLG" "FLAG" NULL,
	"DTNOTYETFLG" "FLAG" NULL,
	"DAYSSINCE30_06_1994" "SMALL_COUNTER" NULL,
	"DAYNUMWK" "TINY_COUNTER" NULL,
	"RELATIVEGAMINGDAY" "SMALL_COUNTER" NULL,
	"WKSTARTDT" "FULL_DATE" NULL,
	"WKENDDT" "FULL_DATE" NULL,
	"WKNUMFISCALYR" "TINY_COUNTER" NULL,
	"WKNUMCLNDRYR" "TINY_COUNTER" NULL,
	"WHOLEWKSSINCE27_06_1994" "SMALL_COUNTER" NULL,
	"ROLLCURR4WKFLG" "FLAG" NULL,
	"ROLLYRINDBYWK" "INDICATOR" NULL,
	"PUBHLDYWKFLG" "FLAG" NULL,
	"SCHLHLDYWKFLG" "FLAG" NULL,
	"SPCLEVNTWKFLG" "FLAG" NULL,
	"MONTHNAME" "SHORT_NAME" NULL,
	"PREVMONNAME" "SHORT_NAME" NULL,
	"MONTHSHORTNAME" "ABBREVIATION" NULL,
	"PREVMONSHORTNAME" "ABBREVIATION" NULL,
	"MONTHNUMINCLNDRYR" "TINY_COUNTER" NULL,
	"PREVCLNDRMONNUM" "TINY_COUNTER" NULL,
	"MONTHNUMINFISCALYR" "TINY_COUNTER" NULL,
	"PREVFISCALMONNUM" "TINY_COUNTER" NULL,
	"MONTHSTARTDT" "FULL_DATE" NULL,
	"MONTHENDDT" "FULL_DATE" NULL,
	"DAYNUMMON" "TINY_COUNTER" NULL,
	"NUMDAYSINMON" "TINY_COUNTER" NULL,
	"LASTDAYINMONFLG" "FLAG" NULL,
	"ROLLYRINDBYMON" "INDICATOR" NULL,
	"QTRNUMFISCALYR" "TINY_COUNTER" NULL,
	"PREVFISCALQTRNUM" "TINY_COUNTER" NULL,
	"QTRLBLFISCALYR" "SHORT_NAME" NULL,
	"PREVFISCALQTRLBL" "SHORT_NAME" NULL,
	"QTRNUMCLNDRYR" "TINY_COUNTER" NULL,
	"PREVCLNDRQTRNUM" "TINY_COUNTER" NULL,
	"QTRLBLCLNDRYR" "SHORT_NAME" NULL,
	"PREVCLNDRQTRLBL" "SHORT_NAME" NULL,
	"DAYNUMQTR" "TINY_COUNTER" NULL,
	"LASTDAYINQTRFLG" "FLAG" NULL,
	"MONTHNUMINQTR" "TINY_COUNTER" NULL,
	"ROLLQTRINDBYMON" "INDICATOR" NULL,
	"FISCALYRNUM" "YEAR_NUMBER" NULL,
	"FISCALYRNAME" "YEAR_NAME" NULL,
	"DAYNUMFISCALYR" "SMALL_COUNTER" NULL,
	"LASTDAYINFISCALYRFLG" "FLAG" NULL,
	"CLNDRYRNUM" "YEAR_NUMBER" NULL,
	"CLNDRYRNAME" "YEAR_NAME" NULL,
	"DAYNUMCLNDRYR" "SMALL_COUNTER" NULL,
	"LASTDAYINCLNDRYRFLG" "FLAG" NULL,
	"LEAPYRFLG" "FLAG" NULL,
	"SEASONNAME" "SHORT_NAME" NULL,
	"VICSCHLHLDYFLG" "FLAG" NULL,
	"VICPUBHLDYFLG" "FLAG" NULL,
	"VICPUBHLDYNAME" "NAME" NULL,
	"DAYBEFOREVICPUBHLDYFLG" "FLAG" NULL,
	"AUSPUBHLDYFLG" "FLAG" NULL,
	"AUSPUBHLDYNAME" "NAME" NULL,
	"DAYBEFOREAUSPUBHLDYFLG" "FLAG" NULL,
	"INTLPUBHLDYFLG" "FLAG" NULL,
	"INTLPUBHLDYNAME" "NAME" NULL,
	"INTLPUBHLDYCNTRYNAME" "NAME" NULL,
	"HrGrpDesc" "SHORT_NAME" NULL,
	"FinYrHalf" "SHORT_NAME" NULL,
	"WeekdayRange" "SHORT_NAME" NULL,
	"DayBreakdown" "SHORT_NAME" NULL,
	"FullClndrDtDesc" "FULL_DATE" NULL,
	"EightHrBandNum" "TINY_COUNTER" NULL,
	"EightHrBandDesc" "BAND_DESCRIPTION" NULL,
	"FinQtrByWk" "TINY_COUNTER" NULL,
	"FinQtrByWkLbl" "ABBREVIATION" NULL,
	"FinYrHalfByWk" "SHORT_NAME" NULL,
	"RelativeGamingWk" "SMALL_COUNTER" NULL,
	"RelativeGamingMonth" "SMALL_COUNTER" NULL,
	"YearID" "SURROGATE_KEY" NULL,
	PRIMARY KEY ( "HOURID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_HOUR" ADD PRIMARY KEY ( "HOURID" ASC );
ALTER TABLE "sybaseadmin"."D_HOUR" ADD CONSTRAINT "FK_D_HOUR_R_DAY_HOU_D_DAY" NOT NULL FOREIGN KEY ( "DAYID" ASC ) REFERENCES "sybaseadmin"."D_DAY" ( "DAYID" );
ALTER TABLE "sybaseadmin"."D_HOUR" ADD CONSTRAINT "FK_D_HOUR_R_MONTH_H_D_MONTH" NOT NULL FOREIGN KEY ( "MONTHID" ASC ) REFERENCES "sybaseadmin"."D_MONTH" ( "MONTHID" );
ALTER TABLE "sybaseadmin"."D_HOUR" ADD CONSTRAINT "FK_D_HOUR_R_WEEK_HO_D_WEEK" NOT NULL FOREIGN KEY ( "WEEKID" ASC ) REFERENCES "sybaseadmin"."D_WEEK" ( "WEEKID" );

ALTER TABLE "sybaseadmin"."F_BriefCam_Cnt_Hourly" ADD CONSTRAINT "F_BC_Cnt_Hr_Fk1" NOT NULL FOREIGN KEY ( "HourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ATS_Hourly_Poll" ADD CONSTRAINT "FK_ATS_Hourly_Poll_Hour" NOT NULL FOREIGN KEY ( "ATSPollHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ATS_Jackpot_Hit" ADD CONSTRAINT "FK_ATS_Jkp_Hit_Paid_Hr" NOT NULL FOREIGN KEY ( "JkptPdHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ATS_Jackpot_Hit" ADD CONSTRAINT "FK_ATS_Jkp_Hit_Start_Hr" NOT NULL FOREIGN KEY ( "JkptHitHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."D_Bus_Hr" ADD CONSTRAINT "FK_Bus_Hr_Hr" NOT NULL FOREIGN KEY ( "HOURID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Hourly" ADD CONSTRAINT "FK_CIM_PROD_HOURLY_HOUR" NOT NULL FOREIGN KEY ( "HOURID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Consolation_Prize_Transactions" ADD CONSTRAINT "FK_Consolation_Prize_Hour" NOT NULL FOREIGN KEY ( "HrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Employee_Table_Swipe" ADD CONSTRAINT "FK_Emp_Tbl_Swipe_End_Hr" FOREIGN KEY ( "EmpSwipeEndHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Employee_Table_Swipe" ADD CONSTRAINT "FK_Emp_Tbl_Swipe_Start_Hr" NOT NULL FOREIGN KEY ( "EmpSwipeStartHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Patron_Entry_Management" ADD CONSTRAINT "FK_EntryChkHr" NOT NULL FOREIGN KEY ( "EntryChkHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ExternalRating" ADD CONSTRAINT "FK_ExternalRating_RatingEndHourID" NOT NULL FOREIGN KEY ( "RatingEndHourId" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ExternalRating" ADD CONSTRAINT "FK_ExternalRating_RatingStartHourID" NOT NULL FOREIGN KEY ( "RatingStartHourId" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_HOUR_GA_D_HOUR" NOT NULL FOREIGN KEY ( "RATINGHOURID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONHOURGAMEAREA" ADD CONSTRAINT "FK_F_GAMING_R_HOUR_GA_D_HOUR" NOT NULL FOREIGN KEY ( "RATINGHOURID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Paging_Transaction" ADD CONSTRAINT "FK_F_PagingTransaction_EndHour" NOT NULL FOREIGN KEY ( "PagingEndHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Paging_Transaction" ADD CONSTRAINT "FK_F_PagingTransaction_StartHour" NOT NULL FOREIGN KEY ( "PagingStartHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_F_POS_SA_R_POS_SAL_D_HOUR_CLS" NOT NULL FOREIGN KEY ( "ChkClsHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_F_POS_SA_R_POS_SAL_D_HOUR_CLS" NOT NULL FOREIGN KEY ( "ChkClsHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_F_POS_SA_R_POS_SAL_D_HOUR_TRANS" NOT NULL FOREIGN KEY ( "TransHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_F_POS_SA_R_POS_SAL_D_HOUR_TRANS" NOT NULL FOREIGN KEY ( "TransHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Adjustment" ADD CONSTRAINT "FK_F_PromoAdj_Day" FOREIGN KEY ( "AdjHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_TableBet_Configuration" ADD CONSTRAINT "FK_F_TableBet_EndHour" FOREIGN KEY ( "TblBetConfigEndHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_TableBet_Configuration" ADD CONSTRAINT "FK_F_TableBet_StartHour" FOREIGN KEY ( "TblBetConfigStartHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_TITO_Transactions" ADD CONSTRAINT "FK_F_TITO_Trans_Hour" NOT NULL FOREIGN KEY ( "TicketHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_EndHr" NOT NULL FOREIGN KEY ( "RatingEndHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Configuration" ADD CONSTRAINT "FK_Jkpt_Config_End_Hr" NOT NULL FOREIGN KEY ( "JkptConfigEndHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Configuration" ADD CONSTRAINT "FK_Jkpt_Config_Start_Hr" NOT NULL FOREIGN KEY ( "JkptConfigStartHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Hit" ADD CONSTRAINT "FK_Jkpt_Hit_HrID" NOT NULL FOREIGN KEY ( "JkptHitHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Hit" ADD CONSTRAINT "FK_Jkpt_Paid_HrID" NOT NULL FOREIGN KEY ( "JkptPdHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_CardedJkptClosePollHr" NOT NULL FOREIGN KEY ( "CardedJkptClosePollHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_CardedJkptOpnPollHr" NOT NULL FOREIGN KEY ( "CardedJkptOpnPollHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_LinkClosePollHr" NOT NULL FOREIGN KEY ( "LinkJkptClosePollHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_LinkOpnPollHr" NOT NULL FOREIGN KEY ( "LinkJkptOpnPollHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Machine_Hourly_Poll" ADD CONSTRAINT "FK_Mac_Hourly_Poll_Hr" NOT NULL FOREIGN KEY ( "GamingMacPollHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingCashBalance" ADD CONSTRAINT "FK_ParkingCshBal_Hr" NOT NULL FOREIGN KEY ( "ParkingCshBalHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingCashFlow" ADD CONSTRAINT "FK_ParkingCshFlow_Hr" NOT NULL FOREIGN KEY ( "ParkingCshFlowHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Parking_Entry_Failure" ADD CONSTRAINT "FK_ParkingEntryFailure_Hr" NOT NULL FOREIGN KEY ( "HourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingPaymentTransaction" ADD CONSTRAINT "FK_ParkingPayTrans_Hr" NOT NULL FOREIGN KEY ( "ParkingPayHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingSystemEvent" ADD CONSTRAINT "FK_ParkingSystEvt_Hr" NOT NULL FOREIGN KEY ( "ParkingSystEvtHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_EntryHr" NOT NULL FOREIGN KEY ( "ParkingEntryHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_ExitHr" NOT NULL FOREIGN KEY ( "ParkingExitHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_LastPayHr" NOT NULL FOREIGN KEY ( "ParkingLastPayHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_BACTRACK_Bet_Activity" ADD CONSTRAINT "FK_Plyr_Prog_BT_Bet_Actvy_Hr" NOT NULL FOREIGN KEY ( "BTHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Check" ADD CONSTRAINT "FK_POS_CHECK_HOUR_CLOSE" NOT NULL FOREIGN KEY ( "ChkClsHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Check" ADD CONSTRAINT "FK_POS_CHECK_HOUR_OPEN" NOT NULL FOREIGN KEY ( "ChkOpnHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Journal_Log" ADD CONSTRAINT "FK_POS_JOURNAL_LOG_CHKCLSHOUR" NOT NULL FOREIGN KEY ( "ChkClsHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Journal_Log" ADD CONSTRAINT "FK_POS_JOURNAL_LOG_CHKOPNHOUR" NOT NULL FOREIGN KEY ( "ChkOpnHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Journal_Log" ADD CONSTRAINT "FK_POS_JOURNAL_LOG_HOUR" NOT NULL FOREIGN KEY ( "JournalLogTransHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_HOUR" NOT NULL FOREIGN KEY ( "ChkOpnHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_HOUR" NOT NULL FOREIGN KEY ( "ChkOpnHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Key_Plyr_Rating" ADD CONSTRAINT "FK_Prog_Key_Plyr_Rating_Hr" NOT NULL FOREIGN KEY ( "KeyPlyrRatingHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Transaction" ADD CONSTRAINT "FK_Promo_Trans_Hr" NOT NULL FOREIGN KEY ( "PromoTransHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Hits" ADD CONSTRAINT "FK_PromotionHits_HitHourID" FOREIGN KEY ( "HitHourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_R_GamRating_Limit_Hit_Hr" NOT NULL FOREIGN KEY ( "LimitHitHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Survey_Response" ADD CONSTRAINT "FK_Survey_Response_Hr" NOT NULL FOREIGN KEY ( "HourId" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Table_Hourly" ADD CONSTRAINT "FK_Tbl_Hourly_Hr" NOT NULL FOREIGN KEY ( "TblHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_TRAFFIC_CNT_HOURLY" ADD CONSTRAINT "FK_Traffic_Cnt_Hourly_HourID" NOT NULL FOREIGN KEY ( "HourID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Customer_Visits" ADD CONSTRAINT "FK_VstEndHr" NOT NULL FOREIGN KEY ( "VstEndHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Customer_Visits" ADD CONSTRAINT "FK_VstStartHr" NOT NULL FOREIGN KEY ( "VstStartHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_Customer_Visits" ADD CONSTRAINT "FK_VstStsCrtHr" NOT NULL FOREIGN KEY ( "VstStsCrtHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );


CREATE HG INDEX "ASIQ_IDX_T292_C1_HG" ON "sybaseadmin"."D_HOUR" ("HOURID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "HG_D_HOUR_YearID" ON "sybaseadmin"."D_HOUR" ("YearID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AUSPUBHLDYFLG_HG" ON "sybaseadmin"."D_HOUR" ("AUSPUBHLDYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AUSPUBHLDYNAME_HG" ON "sybaseadmin"."D_HOUR" ("AUSPUBHLDYNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_CLNDRYRNAME_HG" ON "sybaseadmin"."D_HOUR" ("CLNDRYRNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_CLNDRYRNUM_HG" ON "sybaseadmin"."D_HOUR" ("CLNDRYRNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYBEFOREAUSPUBHLDYFLG_HG" ON "sybaseadmin"."D_HOUR" ("DAYBEFOREAUSPUBHLDYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYBEFOREVICPUBHLDYFLG_HG" ON "sybaseadmin"."D_HOUR" ("DAYBEFOREVICPUBHLDYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DayBreakdown_HG" ON "sybaseadmin"."D_HOUR" ("DayBreakdown" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYID_HG" ON "sybaseadmin"."D_HOUR" ("DAYID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYNAME_HG" ON "sybaseadmin"."D_HOUR" ("DAYNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYNUMCLNDRYR_HG" ON "sybaseadmin"."D_HOUR" ("DAYNUMCLNDRYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYNUMFISCALYR_HG" ON "sybaseadmin"."D_HOUR" ("DAYNUMFISCALYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYNUMMON_HG" ON "sybaseadmin"."D_HOUR" ("DAYNUMMON" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYNUMQTR_HG" ON "sybaseadmin"."D_HOUR" ("DAYNUMQTR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYNUMWK_HG" ON "sybaseadmin"."D_HOUR" ("DAYNUMWK" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYSHORTNAME_HG" ON "sybaseadmin"."D_HOUR" ("DAYSHORTNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DAYSSINCE30_06_1994_HG" ON "sybaseadmin"."D_HOUR" ("DAYSSINCE30_06_1994" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DTNOTYETFLG_HG" ON "sybaseadmin"."D_HOUR" ("DTNOTYETFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EightHrBandDesc_HG" ON "sybaseadmin"."D_HOUR" ("EightHrBandDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EightHrBandNum_HG" ON "sybaseadmin"."D_HOUR" ("EightHrBandNum" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FinQtrByWk_HG" ON "sybaseadmin"."D_HOUR" ("FinQtrByWk" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FinQtrByWkLbl_HG" ON "sybaseadmin"."D_HOUR" ("FinQtrByWkLbl" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FinYrHalf_HG" ON "sybaseadmin"."D_HOUR" ("FinYrHalf" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FinYrHalfByWk_HG" ON "sybaseadmin"."D_HOUR" ("FinYrHalfByWk" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FISCALYRNAME_HG" ON "sybaseadmin"."D_HOUR" ("FISCALYRNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FISCALYRNUM_HG" ON "sybaseadmin"."D_HOUR" ("FISCALYRNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FOURHOURBANDDESC_HG" ON "sybaseadmin"."D_HOUR" ("FOURHOURBANDDESC" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FOURHOURBANDNUM_HG" ON "sybaseadmin"."D_HOUR" ("FOURHOURBANDNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DATE INDEX "IDX_FullClndrDtDesc_DATE" ON "sybaseadmin"."D_HOUR" ("FullClndrDtDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FullClndrDtDesc_HG" ON "sybaseadmin"."D_HOUR" ("FullClndrDtDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DATE INDEX "IDX_FULLDT_DATE" ON "sybaseadmin"."D_HOUR" ("FULLDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_FullDt_HG" ON "sybaseadmin"."D_HOUR" ("FULLDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGHOURDESC_HG" ON "sybaseadmin"."D_HOUR" ("GAMINGHOURDESC" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGHOURNUMWITHINDAY_HG" ON "sybaseadmin"."D_HOUR" ("GAMINGHOURNUMWITHINDAY" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_HOURDESC_HG" ON "sybaseadmin"."D_HOUR" ("HOURDESC" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_HOURNUMWITHINDAY_HG" ON "sybaseadmin"."D_HOUR" ("HOURNUMWITHINDAY" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_HOURSSINCE30_06_1994_HG" ON "sybaseadmin"."D_HOUR" ("HOURSSINCE30_06_1994" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_HrGrpDesc_HG" ON "sybaseadmin"."D_HOUR" ("HrGrpDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_INTLPUBHLDYCNTRYNAME_HG" ON "sybaseadmin"."D_HOUR" ("INTLPUBHLDYCNTRYNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_INTLPUBHLDYFLG_HG" ON "sybaseadmin"."D_HOUR" ("INTLPUBHLDYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_INTLPUBHLDYNAME_HG" ON "sybaseadmin"."D_HOUR" ("INTLPUBHLDYNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LASTDAYINCLNDRYRFLG_HG" ON "sybaseadmin"."D_HOUR" ("LASTDAYINCLNDRYRFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LASTDAYINFISCALYRFLG_HG" ON "sybaseadmin"."D_HOUR" ("LASTDAYINFISCALYRFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LASTDAYINMONFLG_HG" ON "sybaseadmin"."D_HOUR" ("LASTDAYINMONFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LASTDAYINQTRFLG_HG" ON "sybaseadmin"."D_HOUR" ("LASTDAYINQTRFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LEAPYRFLG_HG" ON "sybaseadmin"."D_HOUR" ("LEAPYRFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DATE INDEX "IDX_MONTHENDDT_DATE" ON "sybaseadmin"."D_HOUR" ("MONTHENDDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHENDDT_HG" ON "sybaseadmin"."D_HOUR" ("MONTHENDDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHID_HG" ON "sybaseadmin"."D_HOUR" ("MONTHID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHNAME_HG" ON "sybaseadmin"."D_HOUR" ("MONTHNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHNUMINCLNDRYR_HG" ON "sybaseadmin"."D_HOUR" ("MONTHNUMINCLNDRYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHNUMINFISCALYR_HG" ON "sybaseadmin"."D_HOUR" ("MONTHNUMINFISCALYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHNUMINQTR_HG" ON "sybaseadmin"."D_HOUR" ("MONTHNUMINQTR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHSHORTNAME_HG" ON "sybaseadmin"."D_HOUR" ("MONTHSHORTNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DATE INDEX "IDX_MONTHSTARTDT_DATE" ON "sybaseadmin"."D_HOUR" ("MONTHSTARTDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MONTHSTARTDT_HG" ON "sybaseadmin"."D_HOUR" ("MONTHSTARTDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_NUMDAYSINMON_HG" ON "sybaseadmin"."D_HOUR" ("NUMDAYSINMON" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PEAKDAYFLAG_HG" ON "sybaseadmin"."D_HOUR" ("PEAKDAYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PEAKHOURIND_HG" ON "sybaseadmin"."D_HOUR" ("PEAKHOURIND" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVCLNDRMONNUM_HG" ON "sybaseadmin"."D_HOUR" ("PREVCLNDRMONNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVCLNDRQTRLBL_HG" ON "sybaseadmin"."D_HOUR" ("PREVCLNDRQTRLBL" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVCLNDRQTRNUM_HG" ON "sybaseadmin"."D_HOUR" ("PREVCLNDRQTRNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVFISCALMONNUM_HG" ON "sybaseadmin"."D_HOUR" ("PREVFISCALMONNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVFISCALQTRLBL_HG" ON "sybaseadmin"."D_HOUR" ("PREVFISCALQTRLBL" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVFISCALQTRNUM_HG" ON "sybaseadmin"."D_HOUR" ("PREVFISCALQTRNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVMONNAME_HG" ON "sybaseadmin"."D_HOUR" ("PREVMONNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PREVMONSHORTNAME_HG" ON "sybaseadmin"."D_HOUR" ("PREVMONSHORTNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PUBHLDYWKFLG_HG" ON "sybaseadmin"."D_HOUR" ("PUBHLDYWKFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_QTRLBHGISCALYR_HG" ON "sybaseadmin"."D_HOUR" ("QTRLBLFISCALYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_QTRLBLCLNDRYR_HG" ON "sybaseadmin"."D_HOUR" ("QTRLBLCLNDRYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_QTRNUMCLNDRYR_HG" ON "sybaseadmin"."D_HOUR" ("QTRNUMCLNDRYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_QTRNUMFISCALYR_HG" ON "sybaseadmin"."D_HOUR" ("QTRNUMFISCALYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_RELATIVEGAMINGDAY_HG" ON "sybaseadmin"."D_HOUR" ("RELATIVEGAMINGDAY" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_RelativeGamingMonth_HG" ON "sybaseadmin"."D_HOUR" ("RelativeGamingMonth" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_RelativeGamingWk_HG" ON "sybaseadmin"."D_HOUR" ("RelativeGamingWk" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_ROLLCURR4WKFLG_HG" ON "sybaseadmin"."D_HOUR" ("ROLLCURR4WKFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_ROLLQTRINDBYMON_HG" ON "sybaseadmin"."D_HOUR" ("ROLLQTRINDBYMON" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_ROLLYRINDBYMON_HG" ON "sybaseadmin"."D_HOUR" ("ROLLYRINDBYMON" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_ROLLYRINDBYWK_HG" ON "sybaseadmin"."D_HOUR" ("ROLLYRINDBYWK" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SCHLHLDYWKFLG_HG" ON "sybaseadmin"."D_HOUR" ("SCHLHLDYWKFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SEASONNAME_HG" ON "sybaseadmin"."D_HOUR" ("SEASONNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SPCLEVNTWKFLG_HG" ON "sybaseadmin"."D_HOUR" ("SPCLEVNTWKFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_THREEHOURBANDDESC_HG" ON "sybaseadmin"."D_HOUR" ("THREEHOURBANDDESC" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_THREEHOURBANDNUM_HG" ON "sybaseadmin"."D_HOUR" ("THREEHOURBANDNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_VICPUBHLDYFLG_HG" ON "sybaseadmin"."D_HOUR" ("VICPUBHLDYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_VICPUBHLDYNAME_HG" ON "sybaseadmin"."D_HOUR" ("VICPUBHLDYNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_VICSCHLHLDYFLG_HG" ON "sybaseadmin"."D_HOUR" ("VICSCHLHLDYFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WeekdayRange_HG" ON "sybaseadmin"."D_HOUR" ("WeekdayRange" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WEEKID_HG" ON "sybaseadmin"."D_HOUR" ("WEEKID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WHOLEWKSSINCE27_06_1994_HG" ON "sybaseadmin"."D_HOUR" ("WHOLEWKSSINCE27_06_1994" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DATE INDEX "IDX_WKENDDT_DATE" ON "sybaseadmin"."D_HOUR" ("WKENDDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WKENDDT_HG" ON "sybaseadmin"."D_HOUR" ("WKENDDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WKNUMCLNDRYR_HG" ON "sybaseadmin"."D_HOUR" ("WKNUMCLNDRYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WKNUMFISCALYR_HG" ON "sybaseadmin"."D_HOUR" ("WKNUMFISCALYR" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DATE INDEX "IDX_WKSTARTDT_DATE" ON "sybaseadmin"."D_HOUR" ("WKSTARTDT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_WKSTARTDT_HG" ON "sybaseadmin"."D_HOUR" ("WKSTARTDT" ASC) IN "IQ_ACTIVE_MAIN";
