CREATE TABLE "sybaseadmin"."D_TRANSTYPE" (
		"TRANSTYPEID" "SURROGATE_KEY" NOT NULL,
	"TRANSTYPECODE" "TRANSTYPE" NULL,
	"TRANSTYPEDESC" "SHORT_DESCRIPTION" NULL,
	"LegacyTransCde" "Medium_Cde" NULL,
	"LegacyTransDesc" "LONG_NAME" NULL,
	"ETLJobDtlID" "SURROGATE_KEY" NOT NULL,
	"TransGrp" "SHORT_DESCRIPTION" NULL,
	"SiteID" "SURROGATE_KEY" NOT NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	PRIMARY KEY ( "TRANSTYPEID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_TRANSTYPE" ADD PRIMARY KEY ( "TRANSTYPEID" ASC );
ALTER TABLE "sybaseadmin"."D_TRANSTYPE" ADD CONSTRAINT "FK_TransTyp_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."D_TRANSTYPE" ADD CONSTRAINT "FK_TransType_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );

ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_TRANSAC_D_TRANST" NOT NULL FOREIGN KEY ( "TRANSTYPEID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_Paging_Transaction" ADD CONSTRAINT "FK_F_PagingTransaction_CallType" NOT NULL FOREIGN KEY ( "CallTypeID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_TITO_Transactions" ADD CONSTRAINT "FK_F_TITO_Trans_Trans_Type" NOT NULL FOREIGN KEY ( "TicketTransTypID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_Hotel_Revenue_Day" ADD CONSTRAINT "FK_Hotel_Rev_Dy_Trans_Typ" NOT NULL FOREIGN KEY ( "TranstypeID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_Parking_Day" ADD CONSTRAINT "FK_Parking_Dy_Trans_Typ" NOT NULL FOREIGN KEY ( "TransTypeID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_Parking_Entry_Failure" ADD CONSTRAINT "FK_ParkingEntryFailure_TransTyp" NOT NULL FOREIGN KEY ( "TransTypID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_ParkingPaymentTransaction" ADD CONSTRAINT "FK_ParkingPayTrans_TransTyp" NOT NULL FOREIGN KEY ( "TransTypID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_POS_Check" ADD CONSTRAINT "FK_POS_CHECK_TRANSTYPE" NOT NULL FOREIGN KEY ( "OrderTypeID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_STATUS_ORDTYP" NOT NULL FOREIGN KEY ( "OrderTypeID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_STATUS_REASONCDE" FOREIGN KEY ( "RetReasonID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."tmp_d_promotion_thresholds" ADD CONSTRAINT "FK_PromotionThreshold_PromoTemplateID" NOT NULL FOREIGN KEY ( "PromoTemplateID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_Survey_Profile" ADD CONSTRAINT "FK_Survey_Profile_TransType" NOT NULL FOREIGN KEY ( "PatronClsId" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );


CREATE HG INDEX "ASIQ_IDX_T736_I6_HG" ON "sybaseadmin"."D_TRANSTYPE" ("TRANSTYPEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T841_C6_HG" ON "sybaseadmin"."D_TRANSTYPE" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T841_C8_HG" ON "sybaseadmin"."D_TRANSTYPE" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LegacyTransCde_HG" ON "sybaseadmin"."D_TRANSTYPE" ("LegacyTransCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LegacyTransDesc_HG" ON "sybaseadmin"."D_TRANSTYPE" ("LegacyTransDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_TRANSTYPE" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TransGrp_HG" ON "sybaseadmin"."D_TRANSTYPE" ("TransGrp" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TRANSTYPECODE_HG" ON "sybaseadmin"."D_TRANSTYPE" ("TRANSTYPECODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TRANSTYPEDESC_HG" ON "sybaseadmin"."D_TRANSTYPE" ("TRANSTYPEDESC" ASC) IN "IQ_ACTIVE_MAIN";
