CREATE TABLE "sybaseadmin"."D_CASINOLOCATIONDET" (
		"CASINOLOCDETID" UNSIGNED INT NOT NULL,
	"PTYLOCNUM" SMALLINT NULL,
	"PTYLOCNAME" VARCHAR(35) NULL,
	"CASINOLOC" VARCHAR(50) NOT NULL,
	"LOCTYPCODE" CHAR(1) NULL,
	"EGM_AREA" VARCHAR(5) NULL,
	"EGM_BANK" CHAR(2) NULL,
	"EGM_MACHINE" CHAR(2) NULL,
	"TBLAREA" VARCHAR(8) NULL,
	"PITNUM" CHAR(2) NULL,
	"GAMINGTABLENUM" CHAR(2) NULL,
	"GAMINGAREA" CHAR(1) NULL,
	"CasinoLocDesc" VARCHAR(80) NULL,
	"LocTypName" VARCHAR(30) NULL,
	"GamingAreaName" VARCHAR(15) NULL,
	"EGMAreaName" VARCHAR(35) NULL,
	"EGMZoneCde" VARCHAR(5) NULL,
	"EGMZoneDesc" VARCHAR(30) NULL,
	"EGMBankName" VARCHAR(30) NULL,
	"NumSGStns" TINYINT NULL,
	"GamingAreaSeg" VARCHAR(50) NULL,
	"GamingAreaStrm" VARCHAR(15) NULL,
	"GamingAreaSegName" VARCHAR(35) NULL,
	"MicrosRevCent" VARCHAR(5) NULL,
	"OperaRevCent" VARCHAR(10) NULL,
	"GamingAreaSubSeg" VARCHAR(15) NULL,
	"SiteID" UNSIGNED INT NOT NULL,
	"SctyCde" TINYINT NULL,
	"ETLJobDtlID" UNSIGNED INT NOT NULL,
	"BusOwnName" VARCHAR(35) NULL,
	"OutletTyp" VARCHAR(35) NULL,
	"OutletArea" VARCHAR(35) NULL,
	"OutletStyle" VARCHAR(35) NULL,
	"OutletLvl" VARCHAR(35) NULL,
	"TblNum" VARCHAR(10) NULL,
	"MicrosRevCentDesc" VARCHAR(80) NULL,
	"BusOwnSctyCde" TINYINT NULL,
	"BusOwnID" UNSIGNED INT NULL,
	"LegacyDeptNum" VARCHAR(8) NULL DEFAULT '?',
	"PagingZone" VARCHAR(80) NULL,
	CONSTRAINT "PK_D_CASINOLOCATIONDET" PRIMARY KEY ( "CASINOLOCDETID" ASC )
) IN "IQ_ACTIVE_MAIN";


ALTER TABLE "sybaseadmin"."D_CASINOLOCATIONDET" ADD CONSTRAINT "FK_Casino_Loc_Dtl_BusOwn" FOREIGN KEY ( "BusOwnID" ASC ) REFERENCES "sybaseadmin"."D_Business_Ownership" ( "BusOwnID" );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATIONDET" ADD CONSTRAINT "FK_Casino_Loc_Dtl_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATIONDET" ADD CONSTRAINT "FK_Casino_Loc_Dtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATIONDET" ADD CONSTRAINT "PK_D_CASINOLOCATIONDET" PRIMARY KEY ( "CASINOLOCDETID" ASC );


ALTER TABLE "sybaseadmin"."F_Bill_Acceptance" ADD CONSTRAINT "FK_Bill_Accept_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Hourly" ADD CONSTRAINT "FK_CIM_PROD_HOURLY_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."D_TerminalLocationDet" ADD CONSTRAINT "FK_D_TerminalLocationDet_CasinoLocationDet" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_DACOM_Bonusing" ADD CONSTRAINT "FK_DACOM_Bonus_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Employee_Table_Swipe" ADD CONSTRAINT "FK_Emp_Tbl_Swipe_Loc_Dtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_FATG_Configuration" ADD CONSTRAINT "FK_F_FATG_Config_CasinoLocDet" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Point_of_Sale_Account" ADD CONSTRAINT "FK_F_POINT__R_POINT_O_D_CASINO" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_TableBet_Configuration" ADD CONSTRAINT "FK_F_TableBet_CasinoLoc" FOREIGN KEY ( "CasinolocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_TITO_Movement_Daily" ADD CONSTRAINT "FK_F_TITO_M_R_TITO_MO_D_CASINO" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_TITO_Movement_Monthly" ADD CONSTRAINT "FK_F_TITO_M_R_TITO_MO_D_CASINO" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_TITO_Transactions" ADD CONSTRAINT "FK_F_TITO_Trans_CasinoLocDet" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_LocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Hotel_Revenue_Day" ADD CONSTRAINT "FK_Hotel_Rev_Dy_Casino_Loc_Dtl" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Hotel_Room_Day" ADD CONSTRAINT "FK_Hotel_Room_Dy_Casino_Loc_Dtl" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Configuration" ADD CONSTRAINT "FK_Jkpt_Config_Casino_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Hit" ADD CONSTRAINT "FK_Jkpt_Hit_CasinoLoc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_CasinoLoc" NOT NULL FOREIGN KEY ( "CasinolocdetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Machine_Daily_Revenue" ADD CONSTRAINT "FK_Mac_Daily_Rev_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Machine_Hourly_Poll" ADD CONSTRAINT "FK_Mac_Hourly_Poll_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_MacDailyGameRev" ADD CONSTRAINT "FK_MacDailyGameRev_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Paging_Alert" ADD CONSTRAINT "FK_PagingAlert_CasinoLoc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Paging_Transaction" ADD CONSTRAINT "FK_PagingTransaction_CasinolocDtl" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Parking_Day" ADD CONSTRAINT "FK_Parking_Dy_Casino_Loc_Dtl" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingCashBalance" ADD CONSTRAINT "FK_ParkingCshBal_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingCashFlow" ADD CONSTRAINT "FK_ParkingCshFlow_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Parking_Entry_Failure" ADD CONSTRAINT "FK_ParkingEntryFailure_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingPaymentTransaction" ADD CONSTRAINT "FK_ParkingPayTrans_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlPayID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingSystemEvent" ADD CONSTRAINT "FK_ParkingSystEvt_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CasinoLocDtlID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_CasLocDtlEntry" NOT NULL FOREIGN KEY ( "CasinoLocDtlEntryID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_CasLocDtlExit" NOT NULL FOREIGN KEY ( "CasinoLocDtlExitID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_CasLocDtlPay" NOT NULL FOREIGN KEY ( "CasinoLocDtlLastPayID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Activity" ADD CONSTRAINT "FK_Plyr_Prog_Actvy_LocDet" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_BACTRACK_Bet_Activity" ADD CONSTRAINT "FK_Plyr_Prog_BT_Bet_Actvy_Loc_Dtl" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Point_Of_Sale_Day" ADD CONSTRAINT "FK_Point_Of_Sale_Dy_Casino_Loc_Dtl" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Check" ADD CONSTRAINT "FK_POS_CHECK_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Journal_Log" ADD CONSTRAINT "FK_POS_JOURNAL_LOG_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Journal_Log" ADD CONSTRAINT "FK_POS_JOURNAL_LOG_CASINOLOCDETUWS" NOT NULL FOREIGN KEY ( "UserWorkstationID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Menu_Item_Price" ADD CONSTRAINT "FK_POS_MENU_ITEM_PRICE_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_CASINOLOCDETUWS" NOT NULL FOREIGN KEY ( "UserWorkstationID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_CASINOLOCDETUWS" NOT NULL FOREIGN KEY ( "UserWorkstationID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_TRANSCASINOLOCDET" NOT NULL FOREIGN KEY ( "TransCasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_TRANSCASINOLOCDET" NOT NULL FOREIGN KEY ( "TransCasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_POS_Serving_Period_Configuration" ADD CONSTRAINT "FK_POS_SERVING_PERIOD_CONFIG_CASINOLOCDET" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Key_Plyr_Rating" ADD CONSTRAINT "FK_Prog_Key_Plyr_Rating_Loc_Dtl" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."tmp_F_Plyr_Prog_Key_Plyr_Rating" ADD CONSTRAINT "FK_Prog_Key_Plyr_Rating_Loc_Dtl" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Transaction" ADD CONSTRAINT "FK_Promo_Trans_Loc" NOT NULL FOREIGN KEY ( "PromoTransLocID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Hits" ADD CONSTRAINT "FK_PromotionHits_CasinoLocDtlID" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Survey_Profile" ADD CONSTRAINT "FK_Survey_Profile_CasinoLocDet" NOT NULL FOREIGN KEY ( "CasinoLocDetId" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Survey_Response" ADD CONSTRAINT "FK_Survey_Response_CasinoLocDet" NOT NULL FOREIGN KEY ( "CasinoLocDetId" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Table_Daily" ADD CONSTRAINT "FK_Tbl_Daily_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Table_Hourly" ADD CONSTRAINT "FK_Tbl_Hourly_Loc" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_Table_Jackpot_Contribution" ADD CONSTRAINT "FK_Tbl_Jkpt_Cont_Casino_Loc_Dtl" NOT NULL FOREIGN KEY ( "CasinoLocDetID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );

CREATE HG INDEX "ASIQ_IDX_T100848_C27_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100848_C29_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100848_C38_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("BusOwnID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100848_I41_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("CASINOLOCDETID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_BusOwnName_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("BusOwnName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_BusOwnSctyCde_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("BusOwnSctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_CASINOLOC_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("CASINOLOC" ASC) IN "IQ_ACTIVE_MAIN";
CREATE UNIQUE HG INDEX "IDX_CasinoLoc_TblArea_HG_UNIQ" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("CASINOLOC" ASC, "LOCTYPCODE" ASC, "TBLAREA" ASC, "SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_CasinoLocDesc_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("CasinoLocDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_CasinoLocDesc_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("CasinoLocDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_AREA_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGM_AREA" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_BANK_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGM_BANK" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_MACHINE_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGM_MACHINE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMAreaName_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGMAreaName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMBankName_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGMBankName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_EGMBankName_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGMBankName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMZoneCde_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGMZoneCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMZoneDesc_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("EGMZoneDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGAREA_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GAMINGAREA" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GamingAreaName_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_GamingAreaName_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GamingAreaSeg_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaSeg" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GamingAreaSegName_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaSegName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_GamingAreaSegName_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaSegName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GamingAreaStrm_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaStrm" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GamingAreaSubSeg_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GamingAreaSubSeg" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGTABLENUM_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("GAMINGTABLENUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LegacyDeptNum_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("LegacyDeptNum" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LOCTYPCODE_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("LOCTYPCODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LocTypName_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("LocTypName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_MicrosRevCent_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("MicrosRevCent" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_MicrosRevCentDesc_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("MicrosRevCentDesc" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_NumSGStns_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("NumSGStns" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_OperaRevCent" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("OperaRevCent" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_OutletArea_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("OutletArea" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_OutletLvl_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("OutletLvl" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_OutletStyle_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("OutletStyle" ASC) IN "IQ_ACTIVE_MAIN";
CREATE WD INDEX "IDX_OutletTyp_WD" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("OutletTyp" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PagingZone_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("PagingZone" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PITNUM_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("PITNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PTYLOCNAME_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("PTYLOCNAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PTYLOCNUM_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("PTYLOCNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TBLAREA_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("TBLAREA" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TblNum_HG" ON "sybaseadmin"."D_CASINOLOCATIONDET" ("TblNum" ASC) IN "IQ_ACTIVE_MAIN";

