CREATE TABLE "sybaseadmin"."D_PRODUCTDET" (
		"PRODUCTDETID" "IDENTIFIER" NOT NULL,
	"GAMINGPRODTYP" "TYPE_CODE" NULL,
	"GAMINGACTIVITYCODE" "GAMING_ACTIVITY_CODE" NULL,
	"EGM_GAMECODE" "MANUFACTURER_CODE" NULL,
	"GAMENAME" "LONG_NAME" NULL,
	"SUBGAMECODE" "GAME_CODE" NULL,
	"SUBGAMENAME" "NAME" NULL,
	"TBLMINBET" "U_Money" NULL,
	"TBLLVL" "SMALL_NUMBER" NULL,
	"EGM_DENOM" "DENOMINATION" NULL,
	"JACKPOTFLG" "FLAG" NULL,
	"EGMLines" "TINY_COUNTER" NULL,
	"RwrdLvl" "TINY_COUNTER" NULL,
	"EdgeTheo" "PERCENTAGE" NULL,
	"TblMaxBet" "U_Money" NULL,
	"AltGamingActvyCde" "GAMING_ACTIVITY_CODE" NULL,
	"AltSubGameCde" "GAME_CODE" NULL,
	"AltSubGameName" "NAME" NULL,
	"SiteID" "SURROGATE_KEY" NOT NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	"ETLJobDtlID" "SURROGATE_KEY" NOT NULL,
	"GameTyp" "LONG_NAME" NULL,
	PRIMARY KEY ( "PRODUCTDETID" ASC )
) IN "IQ_ACTIVE_MAIN";


ALTER TABLE "sybaseadmin"."D_PRODUCTDET" ADD PRIMARY KEY ( "PRODUCTDETID" ASC );
ALTER TABLE "sybaseadmin"."D_PRODUCTDET" ADD CONSTRAINT "FK_Prod_Dtl_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."D_PRODUCTDET" ADD CONSTRAINT "FK_Prod_Dtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );

ALTER TABLE "sybaseadmin"."F_ATS_Daily_Revenue" ADD CONSTRAINT "FK_ATS_Daily_Rev_ProductDet" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_ATS_Hourly_Poll" ADD CONSTRAINT "FK_ATS_Hourly_Poll_ProductDet" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_ATS_Jackpot_Hit" ADD CONSTRAINT "FK_ATS_Jkp_Hit_Prod_Det" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Daily" ADD CONSTRAINT "FK_CIM_PROD_DAILY_PRODUCTDET" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Hourly" ADD CONSTRAINT "FK_CIM_PROD_HOURLY_PRODUCTDET" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_DACOM_Bonusing" ADD CONSTRAINT "FK_DACOM_Bonus_Game" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_FATG_Configuration" ADD CONSTRAINT "FK_F_FATG_Config_ProductDet" NOT NULL FOREIGN KEY ( "PRODUCTDETID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_TableBet_Configuration" ADD CONSTRAINT "FK_F_TableBet_ProductDet" FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Game" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_ProductDet" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Machine_Daily_Revenue" ADD CONSTRAINT "FK_Mac_Daily_Rev_Game" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Machine_Hourly_Poll" ADD CONSTRAINT "FK_Mac_Hourly_Poll_Prod" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_MacDailyGameRev" ADD CONSTRAINT "FK_MacDailyGameRev_ProdDtl" NOT NULL FOREIGN KEY ( "ProdDtlID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Activity" ADD CONSTRAINT "FK_Plyr_Prog_Actvy_Prod_Dtl" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_BACTRACK_Bet_Activity" ADD CONSTRAINT "FK_Plyr_Prog_BT_Bet_Actvy_Prod_Dtl" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_PRODUCT_GAMINGRATING" NOT NULL FOREIGN KEY ( "PRODUCTDETID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Key_Plyr_Rating" ADD CONSTRAINT "FK_Prog_Key_Plyr_Rating_Prod_Dtl" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Hits" ADD CONSTRAINT "FK_PromotionHits_ProductDtl" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Table_Daily" ADD CONSTRAINT "FK_Tbl_Daily_Prod" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_Table_Hourly" ADD CONSTRAINT "FK_Tbl_Hourly_Prod" NOT NULL FOREIGN KEY ( "ProductDetID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );

CREATE HG INDEX "ASIQ_IDX_T105176_C19_HG" ON "sybaseadmin"."D_PRODUCTDET" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T105176_C21_HG" ON "sybaseadmin"."D_PRODUCTDET" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T105176_I23_HG" ON "sybaseadmin"."D_PRODUCTDET" ("PRODUCTDETID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AltGamingActvyCde_HG" ON "sybaseadmin"."D_PRODUCTDET" ("AltGamingActvyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AltSubGameCde_HG" ON "sybaseadmin"."D_PRODUCTDET" ("AltSubGameCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AltSubGameName_HG" ON "sybaseadmin"."D_PRODUCTDET" ("AltSubGameName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EdgeTheo_HG" ON "sybaseadmin"."D_PRODUCTDET" ("EdgeTheo" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_DENOM_HG" ON "sybaseadmin"."D_PRODUCTDET" ("EGM_DENOM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_GAMECODE_HG" ON "sybaseadmin"."D_PRODUCTDET" ("EGM_GAMECODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMLines_HG" ON "sybaseadmin"."D_PRODUCTDET" ("EGMLines" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMENAME_HG" ON "sybaseadmin"."D_PRODUCTDET" ("GAMENAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GameTyp_HG" ON "sybaseadmin"."D_PRODUCTDET" ("GameTyp" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGACTIVITYCODE_HG" ON "sybaseadmin"."D_PRODUCTDET" ("GAMINGACTIVITYCODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGPRODTYP_HG" ON "sybaseadmin"."D_PRODUCTDET" ("GAMINGPRODTYP" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_JACKPOTFLG_HG" ON "sybaseadmin"."D_PRODUCTDET" ("JACKPOTFLG" ASC) IN "IQ_ACTIVE_MAIN";
CREATE UNIQUE HG INDEX "IDX_Prod_Dtl_HG_UNIQ" ON "sybaseadmin"."D_PRODUCTDET" ("GAMINGPRODTYP" ASC, "GAMINGACTIVITYCODE" ASC, "EGM_GAMECODE" ASC, "SUBGAMECODE" ASC, "TBLMINBET" ASC, "TblMaxBet" ASC, "TBLLVL" ASC, "EGM_DENOM" ASC, "SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_RwrdLvl_HG" ON "sybaseadmin"."D_PRODUCTDET" ("RwrdLvl" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_PRODUCTDET" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SUBGAMECODE_HG" ON "sybaseadmin"."D_PRODUCTDET" ("SUBGAMECODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SUBGAMENAME_HG" ON "sybaseadmin"."D_PRODUCTDET" ("SUBGAMENAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TBLLVL_HG" ON "sybaseadmin"."D_PRODUCTDET" ("TBLLVL" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TblMaxBet_HG" ON "sybaseadmin"."D_PRODUCTDET" ("TblMaxBet" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TBLMINBET_HG" ON "sybaseadmin"."D_PRODUCTDET" ("TBLMINBET" ASC) IN "IQ_ACTIVE_MAIN";
CREATE CMP INDEX "IDX_TblMinMaxBet_CMP" ON "sybaseadmin"."D_PRODUCTDET" ("TBLMINBET" ASC, "TblMaxBet" ASC) IN "IQ_ACTIVE_MAIN";
