CREATE TABLE "sybaseadmin"."D_PRODUCT" (
		"PRODUCTID" "IDENTIFIER" NOT NULL,
	"GAMINGPRODTYP" "TYPE_CODE" NULL,
	"GAMINGACTIVITYCODE" "GAMING_ACTIVITY_CODE" NULL,
	"GAMENAME" "LONG_NAME" NULL,
	"EGM_DENOM" "DENOMINATION" NULL,
	"EGM_GAMECODE" "MANUFACTURER_CODE" NULL,
	"AltGamingActvyCde" "GAMING_ACTIVITY_CODE" NULL,
	"SiteID" "SURROGATE_KEY" NOT NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	"ETLJobDtlID" "SURROGATE_KEY" NOT NULL,
	PRIMARY KEY ( "PRODUCTID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_PRODUCT" ADD PRIMARY KEY ( "PRODUCTID" ASC );
ALTER TABLE "sybaseadmin"."D_PRODUCT" ADD CONSTRAINT "FK_Prod_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."D_PRODUCT" ADD CONSTRAINT "FK_Prod_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );

ALTER TABLE "sybaseadmin"."F_GAMINGPATRONHOURGAMEAREA" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_PRODUC" NOT NULL FOREIGN KEY ( "PRODUCTID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCT" ( "PRODUCTID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONVISITGAME" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_PRODUC" NOT NULL FOREIGN KEY ( "PRODUCTID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCT" ( "PRODUCTID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_PRODUC" NOT NULL FOREIGN KEY ( "PRODUCTID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCT" ( "PRODUCTID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Config_Product" NOT NULL FOREIGN KEY ( "ProductID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCT" ( "PRODUCTID" );
ALTER TABLE "sybaseadmin"."F_Table_Jackpot_Contribution" ADD CONSTRAINT "FK_Tbl_Jkpt_Cont_Prod" NOT NULL FOREIGN KEY ( "ProdID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCT" ( "PRODUCTID" );

CREATE HG INDEX "ASIQ_IDX_T105177_C10_HG" ON "sybaseadmin"."D_PRODUCT" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T105177_C8_HG" ON "sybaseadmin"."D_PRODUCT" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T105177_I11_HG" ON "sybaseadmin"."D_PRODUCT" ("PRODUCTID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AltGamingActvyCde_HG" ON "sybaseadmin"."D_PRODUCT" ("AltGamingActvyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_DENOM_HG" ON "sybaseadmin"."D_PRODUCT" ("EGM_DENOM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_Gamecode_HG" ON "sybaseadmin"."D_PRODUCT" ("EGM_GAMECODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMENAME_HG" ON "sybaseadmin"."D_PRODUCT" ("GAMENAME" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGACTIVITYCODE_HG" ON "sybaseadmin"."D_PRODUCT" ("GAMINGACTIVITYCODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GAMINGPRODTYP_HG" ON "sybaseadmin"."D_PRODUCT" ("GAMINGPRODTYP" ASC) IN "IQ_ACTIVE_MAIN";
CREATE UNIQUE HG INDEX "IDX_Prod_HG_UNIQ" ON "sybaseadmin"."D_PRODUCT" ("GAMINGPRODTYP" ASC, "GAMINGACTIVITYCODE" ASC, "EGM_DENOM" ASC, "EGM_GAMECODE" ASC, "SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_PRODUCT" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
