CREATE TABLE "sybaseadmin"."D_Site" (
		"SiteID" "SURROGATE_KEY" NOT NULL,
	"SiteNum" "SMALL_COUNTER" NULL,
	"SiteName" "NAME" NULL,
	"SiteGrpName" "SHORT_DESCRIPTION" NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	PRIMARY KEY ( "SiteID" ASC )
) IN "IQ_ACTIVE_MAIN";

ALTER TABLE "sybaseadmin"."D_Site" ADD PRIMARY KEY ( "SiteID" ASC );

ALTER TABLE "sybaseadmin"."D_BriefCam_BAU_Mapping" ADD CONSTRAINT "D_BC_Bau_Fk1" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_BriefCam_Source" ADD CONSTRAINT "D_BC_Src_Fk1" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_BriefCam_Cnt" ADD CONSTRAINT "F_BC_Cnt_Fk2" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_BriefCam_Cnt_Hourly" ADD CONSTRAINT "F_BC_Cnt_Hr_Fk2" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Adjustment_Reason" ADD CONSTRAINT "FK_AdjRsn_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ATS_Daily_Revenue" ADD CONSTRAINT "FK_ATS_Daily_Rev_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ATS_Hourly_Poll" ADD CONSTRAINT "FK_ATS_Hourly_Poll_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ATS_Jackpot_Configuration" ADD CONSTRAINT "FK_ATS_Jkp_Config_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ATS_Jackpot_Hit" ADD CONSTRAINT "FK_ATS_Jkp_Hit_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Bill_Acceptance" ADD CONSTRAINT "FK_Bill_Accept_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Billing_Detail" ADD CONSTRAINT "FK_Billing_Detail_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Budg_Accnt" ADD CONSTRAINT "FK_Budg_Accnt_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Budget_Day" ADD CONSTRAINT "FK_Budg_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Budg_Forecast" ADD CONSTRAINT "FK_Budg_Forecast_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Budget_Month" ADD CONSTRAINT "FK_Budg_Month_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Bus_Dy" ADD CONSTRAINT "FK_Bus_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Bus_Hr" ADD CONSTRAINT "FK_Bus_Hr_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Bus_Month" ADD CONSTRAINT "FK_Bus_Month_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Bus_Wk" ADD CONSTRAINT "FK_Bus_Wk_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATIONDET" ADD CONSTRAINT "FK_Casino_Loc_Dtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_CASINOLOCATION" ADD CONSTRAINT "FK_Casino_Loc_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Daily" ADD CONSTRAINT "FK_CIM_PROD_DAILY_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_CiM_Productivity_Hourly" ADD CONSTRAINT "FK_CIM_PROD_HOURLY_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Consolation_Prize_Transactions" ADD CONSTRAINT "FK_Consolation_Prize_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_CashFlowType" ADD CONSTRAINT "FK_CshFlowTyp_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Promotion_Ticket_Details" ADD CONSTRAINT "FK_D_PROMOT_R_PROMOTI_D_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_TerminalLocationDet" ADD CONSTRAINT "FK_D_TerminalLocationDet_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Voucher" ADD CONSTRAINT "FK_D_Vouch_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_DACOM_Bonusing" ADD CONSTRAINT "FK_DACOM_Bonus_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."tmp_D_Dept_Grp" ADD CONSTRAINT "FK_Dept_Grp_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Department" ADD CONSTRAINT "FK_Dept_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."tmp_D_Department" ADD CONSTRAINT "FK_Dept_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Employee" ADD CONSTRAINT "FK_Emp_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Employee_Table_Swipe" ADD CONSTRAINT "FK_Emp_Tbl_Swipe_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Emp_Leave_Score" ADD CONSTRAINT "FK_EmpLeaveScore_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Emp_Timesheet" ADD CONSTRAINT "FK_EmpTmsheet_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."M_ETL_JobDet" ADD CONSTRAINT "FK_ETLJobDtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ExternalRating" ADD CONSTRAINT "FK_ExternalRating_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_FATG_Configuration" ADD CONSTRAINT "FK_F_FATG_Config_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_MacDailyGameRev" ADD CONSTRAINT "FK_F_MACDAI_R_MACDAIL_D_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Paging_Transaction" ADD CONSTRAINT "FK_F_PagingTransaction_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Marketing_Eligibility_History" ADD CONSTRAINT "FK_F_Patron_Marketing_Eligibility_History_SiteID" FOREIGN KEY ( "SignUpSiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Month_Point_Balance" ADD CONSTRAINT "FK_F_Patron_Month_Point_Balance_SiteID" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Point_of_Sale_Account" ADD CONSTRAINT "FK_F_POINT__R_POINT_O_D_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Adjustment" ADD CONSTRAINT "FK_F_PromoAdj_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_TableBet_Configuration" ADD CONSTRAINT "FK_F_TableBet_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_TITO_Movement_Monthly" ADD CONSTRAINT "FK_F_TITO_M_R_TITO_MO_D_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_TITO_Movement_Daily" ADD CONSTRAINT "FK_F_TITO_M_R_TITO_MO_D_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_TITO_Transactions" ADD CONSTRAINT "FK_F_TITO_Trans_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_GamingLicense" ADD CONSTRAINT "FK_Gaming_Lic_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Config_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_Configuration_Supplement" ADD CONSTRAINT "FK_Gaming_Mac_Config_Suplemnt_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GamingMachine_License_Configuration" ADD CONSTRAINT "FK_Gaming_Mac_Lic_Config_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_GAMINGMACHINE" ADD CONSTRAINT "FK_Gaming_Mac_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONHOURGAMEAREA" ADD CONSTRAINT "FK_Gaming_Patron_Hr_Game_Area_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONMONTH" ADD CONSTRAINT "FK_Gaming_Patron_Month_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONVISITGAME" ADD CONSTRAINT "FK_Gaming_Patron_Visit_Game_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONVISIT" ADD CONSTRAINT "FK_Gaming_Patron_Vist_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGPATRONWEEK" ADD CONSTRAINT "FK_Gaming_Patron_Wk_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_Gaming_Rating_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GCV_Trans" ADD CONSTRAINT "FK_GCVTrans_LocSite" NOT NULL FOREIGN KEY ( "GCVSiteLocID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GCV_Trans" ADD CONSTRAINT "FK_GCVTrans_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Geographics" ADD CONSTRAINT "FK_Geographics_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Hotel_Revenue_Day" ADD CONSTRAINT "FK_Hotel_Rev_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Hotel_Room_Day" ADD CONSTRAINT "FK_Hotel_Room_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Configuration" ADD CONSTRAINT "FK_Jkpt_Config_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Hit" ADD CONSTRAINT "FK_Jkpt_Hit_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Jackpot_Structure" ADD CONSTRAINT "FK_Jkpt_Struc_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."tmp_D_Jackpot_Structure" ADD CONSTRAINT "FK_Jkpt_Struc_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Jackpot_Schedule" ADD CONSTRAINT "FK_JkptSch_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Machine_Configuration_Brand" ADD CONSTRAINT "FK_Mac_Config_Brand_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Machine_Daily_Revenue" ADD CONSTRAINT "FK_Mac_Daily_Rev_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Machine_Hourly_Poll" ADD CONSTRAINT "FK_Mac_Hourly_Poll_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Mailout_Stream_Event" ADD CONSTRAINT "FK_Mailout_Strm_Evt_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Mailout_Stream" ADD CONSTRAINT "FK_Mailout_Strm_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_ManufGameDet" ADD CONSTRAINT "FK_ManufGameDtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Menu_Item_Detail" ADD CONSTRAINT "FK_Menu_Item_Detail_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_OperCostDetails" ADD CONSTRAINT "FK_OperCostDtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_OperCostTrans" ADD CONSTRAINT "FK_OperCostTrans_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_PageEventType" ADD CONSTRAINT "FK_PageEventType_Site" NOT NULL FOREIGN KEY ( "Siteid" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Parking_Validation_Ticket" ADD CONSTRAINT "FK_PakingValidTicket_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Parking_Day" ADD CONSTRAINT "FK_Parking_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ParkingCashBalance" ADD CONSTRAINT "FK_ParkingCshBal_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ParkingCashFlow" ADD CONSTRAINT "FK_ParkingCshFlow_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Parking_Entry_Failure" ADD CONSTRAINT "FK_ParkingEntryFailure_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_ParkingEvent" ADD CONSTRAINT "FK_ParkingEvt_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ParkingPaymentTransaction" ADD CONSTRAINT "FK_ParkingPayTrans_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_ParkingRate" ADD CONSTRAINT "FK_ParkingRate_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ParkingSystemEvent" ADD CONSTRAINT "FK_ParkingSystEvt_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_ParkingTransaction" ADD CONSTRAINT "FK_ParkingTrans_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Accumulating_Snapshot" ADD CONSTRAINT "FK_Patron_Accum_Snapshot_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Patron_Group" ADD CONSTRAINT "FK_Patron_Grp_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_PATRON" ADD CONSTRAINT "FK_Patron_HomeSite" NOT NULL FOREIGN KEY ( "HomeSiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Merge_History" ADD CONSTRAINT "FK_Patron_Merge_Site" NOT NULL FOREIGN KEY ( "MergedFr_SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_PATRON" ADD CONSTRAINT "FK_Patron_SigUpSite" NOT NULL FOREIGN KEY ( "SignUpSiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Work_Table" ADD CONSTRAINT "FK_Patron_Wrk_Tbl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Recent_Activity" ADD CONSTRAINT "FK_PatronRecentActvy_Site" NOT NULL FOREIGN KEY ( "SiteId" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Activity" ADD CONSTRAINT "FK_Plyr_Prog_Actvy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_BACTRACK_Bet_Activity" ADD CONSTRAINT "FK_Plyr_Prog_BT_Bet_Actvy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Day" ADD CONSTRAINT "FK_Plyr_Prog_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Key_Plyr_Profile" ADD CONSTRAINT "FK_Plyr_Prog_Key_Plyr_Profile_Stie" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Key_Plyr_Rating" ADD CONSTRAINT "FK_Plyr_Prog_Key_Plyr_Rating_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Plyr_Prog_Profile" ADD CONSTRAINT "FK_Plyr_Prog_Profile_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Plyr_Prog" ADD CONSTRAINT "FK_Plyr_Prog_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Point_Of_Sale_Day" ADD CONSTRAINT "FK_Point_Of_Sale_Dy_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Check_Detail" ADD CONSTRAINT "FK_POS_CHECK_DETAIL_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_POS_Check" ADD CONSTRAINT "FK_POS_CHECK_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_POS_Journal_Log" ADD CONSTRAINT "FK_POS_JOURNAL_LOG_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_POS_Menu_Item_Price" ADD CONSTRAINT "FK_POS_MENU_ITEM_PRICE_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."tmp_F_POS_Sale_Line_Item_Transaction" ADD CONSTRAINT "FK_POS_SALE_LI_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_POS_Serving_Period_Configuration" ADD CONSTRAINT "FK_POS_SERVING_PERIOD_CONFIG_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_PRODUCTDET" ADD CONSTRAINT "FK_Prod_Dtl_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_PRODUCT" ADD CONSTRAINT "FK_Prod_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Prog_Rptg_Grp" ADD CONSTRAINT "FK_Prog_Rptg_Grp_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Batch_Transaction" ADD CONSTRAINT "FK_PROMO_BAT_TRANS_SITE" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Promotion_Details" ADD CONSTRAINT "FK_Promo_Details_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Transaction" ADD CONSTRAINT "FK_Promo_Trans_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Promotion_Hits" ADD CONSTRAINT "FK_PromotionHits_SiteID" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."tmp_d_promotion_thresholds" ADD CONSTRAINT "FK_PromotionThreshold_SiteID" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Entry_Management" ADD CONSTRAINT "FK_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Customer_Visits" ADD CONSTRAINT "FK_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_CC2_Status_Code" ADD CONSTRAINT "FK_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_LGA_Competitor_Venue_Monthly_Summary" ADD CONSTRAINT "FK_Site_CmptitorVenMnthlySum" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_LGA_Competitor_Venue_Yearly_Summary" ADD CONSTRAINT "FK_Site_CmptitorVenYrlySum" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_LGA_Competitor_Venue" ADD CONSTRAINT "FK_Site_LGACompetitorVenue" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_LGA_EGM_Monthly_Summary" ADD CONSTRAINT "FK_Site_LGAEGMMonthlySum" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_LGA_EGM_Yearly_Summary" ADD CONSTRAINT "FK_Site_LGAEGMYearlySum" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_LGA_Group" ADD CONSTRAINT "FK_Site_LGAGrp" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Membership_CR_Transaction" ADD CONSTRAINT "FK_Site_MbrshpCRTrans" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Membership_Daily" ADD CONSTRAINT "FK_Site_MembshpDaily" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Interest_Snapshot" ADD CONSTRAINT "FK_Site_PatronIntrstSnapshot" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Patron_Membership" ADD CONSTRAINT "FK_Site_PatronMembshp" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Survey_Profile" ADD CONSTRAINT "FK_Survey_Profile_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Survey_Response" ADD CONSTRAINT "FK_Survey_Response_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Table_Daily" ADD CONSTRAINT "FK_Tbl_Daily_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Table_Hourly" ADD CONSTRAINT "FK_Tbl_Hourly_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Table_Jackpot_Contribution" ADD CONSTRAINT "FK_Tbl_Jkpt_Cont_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_Table_Rewards" ADD CONSTRAINT "FK_Tbl_Rewards_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_TRAFFIC_CNT_HOURLY" ADD CONSTRAINT "FK_Traffic_Cnt_Hourly_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_TRAFFIC_CNT" ADD CONSTRAINT "FK_Traffic_Cnt_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_TrafficCounter_BU_Mapping" ADD CONSTRAINT "FK_TrafficCounter_BU_Mapping_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_TrafficCounter" ADD CONSTRAINT "FK_TrafficCounter_Site" FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_TRANSTYPE" ADD CONSTRAINT "FK_TransType_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_VisitType" ADD CONSTRAINT "FK_VisitTyp_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."D_Weather" ADD CONSTRAINT "FK_Weather_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );

CREATE HG INDEX "ASIQ_IDX_T1075_I6_HG" ON "sybaseadmin"."D_Site" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."D_Site" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SiteGrpName_HG" ON "sybaseadmin"."D_Site" ("SiteGrpName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SiteName_HG" ON "sybaseadmin"."D_Site" ("SiteName" ASC) IN "IQ_ACTIVE_MAIN";
CREATE UNIQUE HG INDEX "IDX_SiteNum_HG_UNQ" ON "sybaseadmin"."D_Site" ("SiteNum" ASC) IN "IQ_ACTIVE_MAIN";
