CREATE TABLE "sybaseadmin"."F_GAMINGRATING" (
		"RATINGHOURID" "IDENTIFIER" NOT NULL,
	"PATRONID" "IDENTIFIER" NOT NULL,
	"CASINOLOCATIONID" "IDENTIFIER" NOT NULL,
	"CASINOLOCDETID" "IDENTIFIER" NOT NULL,
	"PRODUCTID" "IDENTIFIER" NOT NULL,
	"PRODUCTDETID" "IDENTIFIER" NOT NULL,
	"GAMINGMACHINEID" "IDENTIFIER" NOT NULL,
	"TRANSTYPEID" "SURROGATE_KEY" NOT NULL,
	"AGEID" "SMALL_IDENTIFIER" NOT NULL,
	"RATINGID" "LEGACY_IDENTIFIER_NUM" NOT NULL,
	"LEGACYPATRONID" "LEGACY_IDENTIFIER_NUM" NOT NULL,
	"RATINGSTARTDTTM" "DATE_AND_TIME" NULL,
	"RATINGENDDTTM" "DATE_AND_TIME" NULL,
	"TURNOVER" "U_Money" NULL,
	"BUYIN" "U_Money" NULL,
	"AVGBET" "U_Money" NULL,
	"ACTUALWIN" "U_Money" NULL,
	"THEOWIN" "U_Money" NULL,
	"JACKPOT" "U_Money" NULL,
	"BONUS" "U_Money" NULL,
	"SECONDSPLAYED" "COUNTER" NULL,
	"HOURSPLAYED" "HOURS_PLAYED" NULL,
	"PNTSEARNED" "COUNTER" NULL,
	"EGM_PNTSEARNED" "COUNTER" NULL,
	"CASINOCASHEARNED" "U_Money" NULL,
	"VIP_PNTSEARNED" "COUNTER" NULL,
	"TBLPNTSEARNED" "COUNTER" NULL,
	"PROGNUM" "MEDIUM_NUMBER" NULL,
	"VALIDCODE" "SMALL_COUNTER" NULL,
	"SUPERID" VARCHAR(10) NULL,
	"DEALERID" VARCHAR(10) NULL,
	"EGMStroke" "MEDIUM_POSITIVE_NUMBER" NULL,
	"GameWins" "SMALL_MONEY" NULL,
	"RatingEndHrID" "ID_Non_Mandatory" NOT NULL,
	"NumBets" "SMALL_COUNTER" NULL,
	"ProgID" "ID_Non_Mandatory" NOT NULL,
	"ProgOfcID" "Tiny_ID_Non_Mandatory" NULL,
	"JnktRatingFlg" "FLAG" NULL,
	"ProgCompValEarned" "SMALL_MONEY" NULL,
	"DeptID" "Small_ID_Non_Mandatory" NOT NULL,
	"TblChipsIn" "U_Money" NULL,
	"TblCshIn" "U_Money" NULL,
	"TblCheqIn" "U_Money" NULL,
	"LimitHitHrID" "ID_Non_Mandatory" NOT NULL,
	"PatronAncillaryCardID" "ID_Non_Mandatory" NOT NULL,
	"StsID" "Small_ID_Non_Mandatory" NOT NULL,
	"LimitHitDtandTm" "DATE_AND_TIME" NULL,
	"SiteID" "SURROGATE_KEY" NOT NULL,
	"SctyCde" "TINY_COUNTER" NULL,
	"LegacyAuditStsCde" "TRANSTYPE" NULL,
	"PntsEarnedFB" "COUNTER" NULL,
	"PntsEarnedHotel" "COUNTER" NULL,
	"PntsEarnedRetl" "COUNTER" NULL,
	"PntsEarnedRetlTency" "COUNTER" NULL,
	"GrossRev" "U_Money" NULL,
	"NetRev" "U_Money" NULL,
	"PointEarningRatio" "Pct_Extended_Accuracy" NULL,
	"ETLJobDtlID" "SURROGATE_KEY" NOT NULL,
	"PntsEarnedOther" "COUNTER" NULL,
	"JkptProdTypID" "SURROGATE_KEY" NOT NULL,
	"LicID" "SURROGATE_KEY" NOT NULL,
	"EGMAdjustedTHEOWIN" "U_Money" NULL DEFAULT 0.0,
	"RatingType" VARCHAR(5) NULL,
	"Terminallocationdetid" UNSIGNED INT NOT NULL,
	"CashlessIn" NUMERIC(20,2) NULL,
	PRIMARY KEY ( "RATINGHOURID" ASC, "PATRONID" ASC, "CASINOLOCATIONID" ASC, "CASINOLOCDETID" ASC, "PRODUCTID" ASC, "PRODUCTDETID" ASC, "GAMINGMACHINEID" ASC, "TRANSTYPEID" ASC, "AGEID" ASC, "RATINGID" ASC, "LEGACYPATRONID" ASC, "SiteID" ASC )
) IN "IQ_ACTIVE_MAIN";


ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD PRIMARY KEY ( "RATINGHOURID" ASC, "PATRONID" ASC, "CASINOLOCATIONID" ASC, "CASINOLOCDETID" ASC, "PRODUCTID" ASC, "PRODUCTDETID" ASC, "GAMINGMACHINEID" ASC, "TRANSTYPEID" ASC, "AGEID" ASC, "RATINGID" ASC, "LEGACYPATRONID" ASC, "SiteID" ASC );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_AGE_GAM_D_AGE" NOT NULL FOREIGN KEY ( "AGEID" ASC ) REFERENCES "sybaseadmin"."D_AGE" ( "AGEID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_GAMINGM_D_GAMING" NOT NULL FOREIGN KEY ( "GAMINGMACHINEID" ASC ) REFERENCES "sybaseadmin"."D_GAMINGMACHINE" ( "GAMINGMACHINEID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_HOUR_GA_D_HOUR" NOT NULL FOREIGN KEY ( "RATINGHOURID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_CASINO" NOT NULL FOREIGN KEY ( "CASINOLOCATIONID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATION" ( "CASINOLOCID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_SUBGAME_D_PRODUC" NOT NULL FOREIGN KEY ( "PRODUCTID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCT" ( "PRODUCTID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_F_GAMING_R_TRANSAC_D_TRANST" NOT NULL FOREIGN KEY ( "TRANSTYPEID" ASC ) REFERENCES "sybaseadmin"."D_TRANSTYPE" ( "TRANSTYPEID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_Gaming_Rating_Prog" NOT NULL FOREIGN KEY ( "ProgID" ASC ) REFERENCES "sybaseadmin"."D_Plyr_Prog" ( "ProgID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_Gaming_Rating_Site" NOT NULL FOREIGN KEY ( "SiteID" ASC ) REFERENCES "sybaseadmin"."D_Site" ( "SiteID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_CasinoLocDtl" NOT NULL FOREIGN KEY ( "CASINOLOCDETID" ASC ) REFERENCES "sybaseadmin"."D_CASINOLOCATIONDET" ( "CASINOLOCDETID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_EndHr" NOT NULL FOREIGN KEY ( "RatingEndHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_ETLJobDtl" NOT NULL FOREIGN KEY ( "ETLJobDtlID" ASC ) REFERENCES "sybaseadmin"."M_ETL_JobDet" ( "ETLJobDtlID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_Lic" NOT NULL FOREIGN KEY ( "LicID" ASC ) REFERENCES "sybaseadmin"."D_GamingLicense" ( "LicID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_GamingRating_TerminallocDtl" FOREIGN KEY ( "Terminallocationdetid" ASC ) REFERENCES "sybaseadmin"."D_TerminalLocationDet" ( "TerminalLocationDetID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_Patron_GameRating_JkptProdType" NOT NULL FOREIGN KEY ( "JkptProdTypID" ASC ) REFERENCES "sybaseadmin"."D_jackpot_product_type" ( "JkptProdTypID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_Patron_GameRating_PatAncillaryCard" NOT NULL FOREIGN KEY ( "PatronAncillaryCardID" ASC ) REFERENCES "sybaseadmin"."D_PATRON" ( "PATRONID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_PATRON_GAMINGRATING" NOT NULL FOREIGN KEY ( "PATRONID" ASC ) REFERENCES "sybaseadmin"."D_PATRON" ( "PATRONID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_PRODUCT_GAMINGRATING" NOT NULL FOREIGN KEY ( "PRODUCTDETID" ASC ) REFERENCES "sybaseadmin"."D_PRODUCTDET" ( "PRODUCTDETID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_R_GamRating_Limit_Hit_Hr" NOT NULL FOREIGN KEY ( "LimitHitHrID" ASC ) REFERENCES "sybaseadmin"."D_HOUR" ( "HOURID" );
ALTER TABLE "sybaseadmin"."F_GAMINGRATING" ADD CONSTRAINT "FK_Sts_Cde_Gaming_Rating" NOT NULL FOREIGN KEY ( "StsID" ASC ) REFERENCES "sybaseadmin"."D_Status_Code" ( "StsID" );


CREATE HG INDEX "ASIQ_IDX_T100876_C1_HG" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGHOURID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C2_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PATRONID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C3_HG" ON "sybaseadmin"."F_GAMINGRATING" ("CASINOLOCATIONID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C34_HG" ON "sybaseadmin"."F_GAMINGRATING" ("RatingEndHrID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C36_HG" ON "sybaseadmin"."F_GAMINGRATING" ("ProgID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C4_HG" ON "sybaseadmin"."F_GAMINGRATING" ("CASINOLOCDETID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C44_HG" ON "sybaseadmin"."F_GAMINGRATING" ("LimitHitHrID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C45_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PatronAncillaryCardID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C46_HG" ON "sybaseadmin"."F_GAMINGRATING" ("StsID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C48_HG" ON "sybaseadmin"."F_GAMINGRATING" ("SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C5_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PRODUCTID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C58_HG" ON "sybaseadmin"."F_GAMINGRATING" ("ETLJobDtlID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C6_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PRODUCTDETID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C60_HG" ON "sybaseadmin"."F_GAMINGRATING" ("JkptProdTypID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C61_HG" ON "sybaseadmin"."F_GAMINGRATING" ("LicID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C64_HG" ON "sybaseadmin"."F_GAMINGRATING" ("Terminallocationdetid" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C7_HG" ON "sybaseadmin"."F_GAMINGRATING" ("GAMINGMACHINEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C8_HG" ON "sybaseadmin"."F_GAMINGRATING" ("TRANSTYPEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_C9_HG" ON "sybaseadmin"."F_GAMINGRATING" ("AGEID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "ASIQ_IDX_T100876_I64_HG" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGHOURID" ASC, "PATRONID" ASC, "CASINOLOCATIONID" ASC, "CASINOLOCDETID" ASC, "PRODUCTID" ASC, "PRODUCTDETID" ASC, "GAMINGMACHINEID" ASC, "TRANSTYPEID" ASC, "AGEID" ASC, "RATINGID" ASC, "LEGACYPATRONID" ASC, "SiteID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE CMP INDEX "IDX_ACT_THEO_WIN_CMP" ON "sybaseadmin"."F_GAMINGRATING" ("ACTUALWIN" ASC, "THEOWIN" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_ACTUALWIN_HG" ON "sybaseadmin"."F_GAMINGRATING" ("ACTUALWIN" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_AVGBET_HG" ON "sybaseadmin"."F_GAMINGRATING" ("AVGBET" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_BONUS_HG" ON "sybaseadmin"."F_GAMINGRATING" ("BONUS" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_BUYIN_HG" ON "sybaseadmin"."F_GAMINGRATING" ("BUYIN" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_CASINOCASHEARNED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("CASINOCASHEARNED" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_DEALERID_HG" ON "sybaseadmin"."F_GAMINGRATING" ("DEALERID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGM_PNTSEARNED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("EGM_PNTSEARNED" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMAdjustedTHEOWIN_HG" ON "sybaseadmin"."F_GAMINGRATING" ("EGMAdjustedTHEOWIN" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_EGMStroke_HG" ON "sybaseadmin"."F_GAMINGRATING" ("EGMStroke" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GameWins_HG" ON "sybaseadmin"."F_GAMINGRATING" ("GameWins" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_GrossRev_HG" ON "sybaseadmin"."F_GAMINGRATING" ("GrossRev" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_HOURSPLAYED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("HOURSPLAYED" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_JACKPOT_HG" ON "sybaseadmin"."F_GAMINGRATING" ("JACKPOT" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_JnktRatingFlg_HG" ON "sybaseadmin"."F_GAMINGRATING" ("JnktRatingFlg" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LegacyAuditStsCde_HG" ON "sybaseadmin"."F_GAMINGRATING" ("LegacyAuditStsCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LEGACYPATRONID_HG" ON "sybaseadmin"."F_GAMINGRATING" ("LEGACYPATRONID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DTTM INDEX "IDX_LimitHitDtandTm_DTT" ON "sybaseadmin"."F_GAMINGRATING" ("LimitHitDtandTm" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_LimitHitDtandTm_HG" ON "sybaseadmin"."F_GAMINGRATING" ("LimitHitDtandTm" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_NetRev_HG" ON "sybaseadmin"."F_GAMINGRATING" ("NetRev" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_NumBets_HG" ON "sybaseadmin"."F_GAMINGRATING" ("NumBets" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PNTSEARNED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PNTSEARNED" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PntsEarnedFB_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PntsEarnedFB" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PntsEarnedHotel_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PntsEarnedHotel" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PntsEarnedOther_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PntsEarnedOther" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PntsEarnedRetl_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PntsEarnedRetl" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PntsEarnedRetlTency_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PntsEarnedRetlTency" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PointEarningRatio_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PointEarningRatio" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_ProgCompValEarned_HG" ON "sybaseadmin"."F_GAMINGRATING" ("ProgCompValEarned" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_PROGNUM_HG" ON "sybaseadmin"."F_GAMINGRATING" ("PROGNUM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DTTM INDEX "IDX_RATINGENDDTTM_DTTM" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGENDDTTM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_RATINGENDDTTM_HG" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGENDDTTM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE DTTM INDEX "IDX_RATINGSTARTDTTM_DTTM" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGSTARTDTTM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_RATINGSTARTDTTM_HG" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGSTARTDTTM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SctyCde_HG" ON "sybaseadmin"."F_GAMINGRATING" ("SctyCde" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SECONDSPLAYED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("SECONDSPLAYED" ASC) IN "IQ_ACTIVE_MAIN";
CREATE CMP INDEX "IDX_START_END_DATE_CMP" ON "sybaseadmin"."F_GAMINGRATING" ("RATINGSTARTDTTM" ASC, "RATINGENDDTTM" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_SUPERID_HG" ON "sybaseadmin"."F_GAMINGRATING" ("SUPERID" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TblCheqIn_HG" ON "sybaseadmin"."F_GAMINGRATING" ("TblCheqIn" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TblChipsIn_HG" ON "sybaseadmin"."F_GAMINGRATING" ("TblChipsIn" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TblCshIn_HG" ON "sybaseadmin"."F_GAMINGRATING" ("TblCshIn" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TBLPNTSEARNED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("TBLPNTSEARNED" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_THEOWIN_HG" ON "sybaseadmin"."F_GAMINGRATING" ("THEOWIN" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_TURNOVER_HG" ON "sybaseadmin"."F_GAMINGRATING" ("TURNOVER" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_VALIDCODE_HG" ON "sybaseadmin"."F_GAMINGRATING" ("VALIDCODE" ASC) IN "IQ_ACTIVE_MAIN";
CREATE HG INDEX "IDX_VIP_PNTSEARNED_HG" ON "sybaseadmin"."F_GAMINGRATING" ("VIP_PNTSEARNED" ASC) IN "IQ_ACTIVE_MAIN";




